ALTER TABLE users
  ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT '',
  ADD COLUMN IF NOT EXISTS about TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS interests TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS age INTEGER DEFAULT 0;